
from django.urls import path
from .views import (
    CoachAuth,
    coach_bio,
    coach_videos,
    coach_playlist,
    add_to_playlist,
    keywords_equipments,
    get_coach_id,
    videos,
    associated_users,
    handle_toggle_section,
    review,
    testimonial,
    comments,
    no_of_played_times,
    no_of_users_who_have_seen,
    avg_view_time,
    no_of_playlists_the_video_is_in,
    likes,
    video_access,
    public_videos,
    allowed_videos
)

urlpatterns = [
    path('coach/login/', CoachAuth.coach_login),
    path('coach/register/', CoachAuth.coach_register),
    path('coach/forgot-password/', CoachAuth.coach_forgot_password),
    path('coach/verify-otp/', CoachAuth.coach_verify_otp),
    path('coach/reset-password/', CoachAuth.coach_change_password),
    path('coach/bio/', coach_bio),
    path('coach/videos/', coach_videos),
    path('coach/playlists/', coach_playlist),
    path('coach/add-to-playlist/', add_to_playlist),
    path('coach/keywords/equipments/', keywords_equipments),
    path('coach/get_coach_id/', get_coach_id),
    path('videos/', videos),
    path('coach/associated-users/', associated_users),
    path('coach/toggle-section/', handle_toggle_section),
    path('review/', review),
    path('testimonial/', testimonial),
    path('comments/', comments),
    path('no-of-played-times/', no_of_played_times),
    path('no-of-users-who-have-seen/', no_of_users_who_have_seen),
    path('avg-view-time/', avg_view_time),
    path('no-of-playlists-the-video-is-in/', no_of_playlists_the_video_is_in),
    path('likes/', likes),
    path('video-access/', video_access),
    path('public-videos/', public_videos),
    path('allowed-videos/', allowed_videos),
]
