# Generated by Django 2.2.6 on 2019-11-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachregister',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
