# Generated by Django 2.2.6 on 2019-11-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('banner', models.FileField(blank=True, null=True, upload_to='')),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_logo', to='coach.coachRegister')),
            ],
        ),
    ]
