# Generated by Django 2.2.7 on 2019-11-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_coachbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachbio',
            name='banner',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='coachbio',
            name='logo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
