# Generated by Django 2.2.7 on 2019-11-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_auto_20191109_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachregister',
            name='updated_bio',
            field=models.BooleanField(default=False),
        ),
    ]
