# Generated by Django 2.2.7 on 2019-11-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_coachregister_updated_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachbio',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_bio', to='coach.coachRegister'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                ('equipments', models.CharField(blank=True, max_length=256, null=True)),
                ('calories', models.CharField(blank=True, max_length=256, null=True)),
                ('duration', models.CharField(blank=True, max_length=256, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_videos', to='coach.coachRegister')),
            ],
        ),
    ]
