# Generated by Django 2.2.7 on 2019-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_auto_20191110_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
