# Generated by Django 2.2.7 on 2019-11-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_auto_20191110_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                ('level', models.CharField(blank=True, max_length=256, null=True)),
                ('duration', models.CharField(blank=True, max_length=256, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_playlist', to='coach.coachRegister')),
            ],
        ),
    ]
