# Generated by Django 2.2.7 on 2019-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_video_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachbio',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
