# Generated by Django 2.2.7 on 2019-12-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_associatedusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociatedUsers',
        ),
    ]
