# Generated by Django 2.2.7 on 2019-12-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coach', '0015_associateduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssociatedUser',
            new_name='Associated',
        ),
    ]
