# Generated by Django 2.2.7 on 2019-12-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_auto_20191211_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Associated',
        ),
    ]
