# Generated by Django 2.2.7 on 2020-01-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coach', '0022_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_played_times', models.CharField(blank=True, max_length=256, null=True)),
                ('no_of_users_allowed', models.CharField(blank=True, max_length=256, null=True)),
                ('no_of_users_who_have_seen', models.CharField(blank=True, max_length=256, null=True)),
                ('avg_view_time', models.CharField(blank=True, max_length=256, null=True)),
                ('no_of_playlists_the_vieos_is_in', models.CharField(blank=True, max_length=256, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='coach.coachRegister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='user.userRegister')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='coach.Video')),
            ],
        ),
    ]
