# Generated by Django 2.2.7 on 2020-01-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coach', '0024_auto_20200129_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgViewTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_view_time', models.CharField(blank=True, max_length=256, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avgviewtime', to='coach.coachRegister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avgviewtime', to='user.userRegister')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avgviewtime', to='coach.Video')),
            ],
        ),
        migrations.CreateModel(
            name='NoOfPlayedTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_played_times', models.CharField(blank=True, max_length=256, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofplayedtimes', to='coach.coachRegister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofplayedtimes', to='user.userRegister')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofplayedtimes', to='coach.Video')),
            ],
        ),
        migrations.CreateModel(
            name='NoOfUsersWhoHaveSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_users_who_have_seen', models.CharField(blank=True, max_length=256, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofuserswhohaveseen', to='coach.coachRegister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofuserswhohaveseen', to='user.userRegister')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofuserswhohaveseen', to='coach.Video')),
            ],
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
