# Generated by Django 2.2.7 on 2020-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0025_auto_20200129_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgviewtime',
            name='avg_view_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noofplayedtimes',
            name='no_of_played_times',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noofuserswhohaveseen',
            name='no_of_users_who_have_seen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
