# Generated by Django 2.2.7 on 2020-01-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0026_auto_20200129_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoOfUsersWhoHaveSeen',
        ),
    ]
