# Generated by Django 2.2.7 on 2020-01-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coach', '0027_delete_noofuserswhohaveseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoOfUsersWhoHaveSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_users_who_have_seen', models.IntegerField(blank=True, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofuserswhohaveseen', to='coach.coachRegister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofuserswhohaveseen', to='user.userRegister')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noofuserswhohaveseen', to='coach.Video')),
            ],
        ),
    ]
