# Generated by Django 2.2.7 on 2020-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0028_noofuserswhohaveseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noofuserswhohaveseen',
            name='coach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noofuserswhohaveseen',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noofuserswhohaveseen',
            name='video',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
