# Generated by Django 2.2.7 on 2020-01-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0029_auto_20200129_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noofuserswhohaveseen',
            old_name='coach',
            new_name='coach_id',
        ),
        migrations.RenameField(
            model_name='noofuserswhohaveseen',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='noofuserswhohaveseen',
            old_name='video',
            new_name='video_id',
        ),
    ]
