# Generated by Django 2.2.7 on 2020-01-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0030_auto_20200129_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgviewtime',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='avgviewtime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='avgviewtime',
            name='video',
        ),
        migrations.AddField(
            model_name='avgviewtime',
            name='coach_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avgviewtime',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avgviewtime',
            name='video_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
