# Generated by Django 2.2.7 on 2020-01-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0031_auto_20200130_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgviewtime',
            name='avg_view_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
