# Generated by Django 2.2.7 on 2020-02-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0033_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='accesstype',
            field=models.IntegerField(default=1),
        ),
    ]
