# Generated by Django 2.2.7 on 2020-02-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coach', '0034_video_accesstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAccessForPrivateVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_access_for_private_videos', to='user.userRegister')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_access_for_private_videos', to='coach.Video')),
            ],
        ),
    ]
